---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: "my_password"
      prompt: "Enter password"
      private: true

  pre_tasks:
    # - name: add github to known_hosts
    #   file: path=~/.ssh mode=0700 state=directory
    #   lineinfile: dest=~/.ssh/known_hosts create=yes state=present line='{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}' regexp='^github.com'

    - name: ensure homebrew is installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: fail if homebrew is not installed
      fail:
        msg: homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: installing homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  roles:
    - role: elliotweiser.osx-command-line-tools
  tasks:
    - name: generate ssh-key
      command: creates=~/.ssh/id_rsa ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''

    - include_tasks: dotfiles.yml
      when: configure_dotfiles

    - name: upgrade homebrew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    # Tap
    - name: ensure taps are tapped.
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_taps }}"

    # Brew
    - name: install homebrew packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present

    # Cask
    - name: install homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
        install_options: force
      with_items: "{{ cask_packages }}"

    - name: upgrade homebrew casks
      homebrew_cask:
        upgrade_all: true

    # - name: set up bash for user
    #   hosts: localhost
    #   become: no
    #   vars:
    #     the_user: "{{ ansible_user_id }}"
    #   tasks:
    #     - name: change user shell to bash
    #       become: yes
    #       user:
    #         name: "{{ the_user }}"
    #         shell: /usr/local/bin/bash

    #- name: install npm modules
    #  npm: name={{item}} global=yes
    #  with_items: '{{ npm_modules }}'

    # - name: install ffmpeg with options
    #   homebrew: name=ffmpeg install_options='with-fdk-aac,with-freetype,with-libvo-aacenc,with-libvorbis,with-libvpx, with-openjpeg,with-rtmpdump,with-theora,with-tools'

    - name: remove outdated brew versions from the cellar
      command: brew cleanup
