---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  pre_tasks:
    - file: path=~/.ssh mode=0700 state=directory
    - lineinfile: dest=~/.ssh/known_hosts create=yes state=present line="{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}" regexp='^github.com'

  tasks:
    - name: generate ssh-key
      command: creates=~/.ssh/id_rsa ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
    - include: dotfiles.yml

    - name: upgrade homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes

    # Tap
    - name: ensure taps are tapped.
      homebrew_tap: "tap={{ item }} state=present"
      with_items: "{{ brew_taps }}"

    # Brew
    - name: install homebrew packages
      homebrew: "name={{ brew_packages }} state=present"

    - name: install homebrew package(s) with brew options
      homebrew: name={{ item.pkg }} install_options={{ item.opts }} state={{ item.state|default("latest") }}
      with_items: "{{ brew_pkg_with_opts }}"

    # Cask
    - name: install homebrew casks
      #homebrew_cask: name={{item}} state=present install_options="appdir=homebrew_cask_appdir"
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

    - name: upgrade homebrew casks
      homebrew_cask: upgrade_all=true

    #- name: install npm modules
    #  npm: name={{item}} global=yes
    #  with_items: "{{ npm_modules }}"

    - name: install maven
      homebrew: name={{item}} state=present
      with_items:
      - maven # requires java

    - name: install ffmpeg with options
      homebrew: name=ffmpeg install_options="with-fdk-aac,with-freetype,with-libvo-aacenc,with-libvorbis,with-libvpx, with-openjpeg,with-rtmpdump,with-theora,with-tools"

    - name: remove outdated brew versions from the cellar
      command: brew cleanup
